kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: pure-block-delay-binding
  labels:
    kubernetes.io/cluster-service: "true"
provisioner: pure-csi
volumeBindingMode: WaitForFirstConsumer
parameters:
    backend: block
