apiVersion: v1
kind: Pod
metadata:
  name: nginx-file
spec:
  volumes:
  - name: pure-vol
    persistentVolumeClaim:
        claimName: pure-claim-file
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: pure-vol
      mountPath: /data
    ports:
    - containerPort: 80
