apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshot
metadata:
  name: volumesnapshot-1
spec:
  volumeSnapshotClassName: pure-snapshotclass
  source:
     persistentVolumeClaimName: pure-claim
