kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: pure-block-xfs
  labels:
    kubernetes.io/cluster-service: "true"
provisioner: pure-csi
parameters:
    backend: block
    csi.storage.k8s.io/fstype: xfs
    createoptions: -q
mountOptions:
      - discard
