apiVersion: v1
kind: Pod
metadata:
  name: nginx-raw
spec:
  # Specify a volume that uses the claim defined in pvc.yaml
  volumes:
    - name: pure-vol
      persistentVolumeClaim:
        claimName: pvc-import
  containers:
    - name: nginx
      image: nginx
      # Configure a device mount for the volume we defined above
      volumeDevices:
        - name: pure-vol
          devicePath: /dev/pure-block-device
      ports:
        - containerPort: 80
