apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  # Specify a volume that uses the claim defined in pvc.yaml
  volumes:
  - name: pure-vol
    persistentVolumeClaim:
        claimName: pure-claim-raw-block
  containers:
  - name: nginx
    image: nginx
    # Configure a mount for the volume We define above
    volumeMounts:
    - name: pure-vol
      mountPath: /data
    ports:
    - containerPort: 80
