kind: PersistentVolumeClaim
apiVersion: v1
metadata:
    # creates a new pvc and volume from a snapshot, must know snapshot name
    name: pure-fa-snapshot-claim
    annotations:
      snapshot.beta.purestorage.com/name: k8s-pvc-da279c04-b6be-11e8-9937-0050569f0575.1
spec:
     accessModes:
       - ReadWriteOnce
    # storage size must be exact same as snapshot
     resources:
       requests:
         storage: 10Gi
     # Matches the name defined in deployment/storageclass.yaml
     storageClassName: pure-block