arrays:
  FlashArrays:
    - MgmtEndPoint: "1.1.1.1"
      APIToken: "token000"
      Labels:
        local.cluster/rack: "38"
        failure-domain.beta.kubernetes.io/zone: "WEST"
    - MgmtEndPoint: "1.1.1.3"
      APIToken: "token0001"
      Labels:
        local.cluster/rack: "40"
        failure-domain.beta.kubernetes.io/zone: "EAST"

orchestrator:
  k8s:
   flexBaseDir: /var/lib/kubelet/volume-plugins/
   flexPath: /var/lib/kubelet/volume-plugins/