kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: pure-file
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
